[tool.poetry]
name = "hydownloader"
version = "0.10.0"
description = "Download stuff like Hydrus does."
authors = ["thatfuckingbird"]
license = "AGPL-3.0-or-later"

[tool.poetry.scripts]
hydownloader-importer = "hydownloader.importer:main"
hydownloader-anchor-exporter = "hydownloader.anchor_exporter:main"
hydownloader-daemon = "hydownloader.daemon:main"
hydownloader-tools = "hydownloader.tools:main"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.1"
bottle = "^0.12.19"
gallery-dl = "^1.20.1"
youtube_dl = "^2021.6.6"
yt-dlp = "^2021.11.10"
hydrus-api = "^3.22.5"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pylint = "^2.8.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
