[tool.poetry]
name = "hydownloader"
version = "0.1.0"
description = "Download stuff like Hydrus does."
authors = ["thatfuckingbird"]
license = "AGPL-3.0-or-later"

[tool.poetry.scripts]
hydownloader-importer = "hydownloader.importer:main"
hydownloader-anchor-exporter = "hydownloader.anchor_exporter:main"
hydownloader-daemon = "hydownloader.daemon:main"
hydownloader-tools = "hydownloader.tools:main"
hydownloader-metadata-server = "hydownloader.metadata_server:main"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.1"
bottle = "^0.12.19"
gallery-dl = "^1.18.3"
youtube_dl = "^2021.6.6"
hydrus-api = "^2.14.3"

[tool.poetry.dev-dependencies]
Nuitka = "^0.6.14"
pylint = "^2.8.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
