[tool.poetry]
name = "hydownloader"
version = "0.1.0"
description = "Download stuff like Hydrus does."
authors = ["thatfuckingbird"]
license = "AGPL-3.0-or-later"

[tool.poetry.scripts]
hydownloader-importer = "hydownloader.importer:main"
hydownloader-anchor-exporter = "hydownloader.anchor_exporter:main"
hydownloader-daemon = "hydownloader.daemon:main"
hydownloader-tools = "hydownloader.tools:main"

[tool.poetry.dependencies]
python = "^3.9"
click = "^7.1.2"
bottle = "^0.12.19"
gallery-dl = "^1.17.4"
youtube_dl = "^2021.4.26"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
